Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -81,7 +81,7 @@ jobs:
       - name: Test if statement using not equal (again)
         if: ${{ env.LARGER_THAN_0 != 1 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: LARGER_THAN_0 != 1 should be false." && exit 1
       - name: Test if statement using not equal
         id: test_not_equal_again
         if: env.SMALLER_THAN_0 != 0
@@ -89,7 +89,7 @@ jobs:
       - name: Test if statement using not equal without {{ }} (again)
         if: env.LARGER_THAN_0 != 1
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: LARGER_THAN_0 != 1 without {{ }} should be false." && exit 1
       - name: Test if statement using less than
         id: test_less_than
         if: ${{ env.SMALLER_THAN_0 < 0 }}
@@ -97,7 +97,7 @@ jobs:
       - name: Test if statement using less than (again)
         if: ${{ env.SMALLER_THAN_0 < -2 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 < -2 should be false." && exit 1
       - name: Test if statement using less than or equal
         id: test_less_than_or_equal
         if: ${{ env.SMALLER_THAN_0 <= -1 }}
@@ -105,7 +105,7 @@ jobs:
       - name: Test if statement using less than or equal (again)
         if: ${{ env.SMALLER_THAN_0 <= -2 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 <= -2 should be false." && exit 1
       - name: Test if statement using greater than
         id: test_greater_than
         if: ${{ env.SMALLER_THAN_0 > -2 }}
@@ -113,7 +113,7 @@ jobs:
       - name: Test if statement using greater than (again)
         if: ${{ env.SMALLER_THAN_0 > 0 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 > 0 should be false." && exit 1
       - name: Test if statement using greater than or equal
         id: test_greater_than_or_equal
         if: ${{ env.SMALLER_THAN_0 >= -1 }}
@@ -121,7 +121,7 @@ jobs:
       - name: Test if statement using greater than or equal (again)
         if: ${{ env.SMALLER_THAN_0 >= 0 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 >= 0 should be false." && exit 1
       - name: Test if statement using equal
         id: test_equal
         if: ${{ env.SMALLER_THAN_0 == -1 }}
@@ -129,7 +129,7 @@ jobs:
       - name: Test if statement using equal (again)
         if: ${{ env.SMALLER_THAN_0 == 0 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 == 0 should be false." && exit 1
       - name: Test if statement using not
         id: test_not
         if: ${{ !(env.SMALLER_THAN_0 == 0) }}
@@ -137,7 +137,7 @@ jobs:
       - name: Test if statement using not (again)
         if: ${{ !(env.SMALLER_THAN_0 == -1) }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: SMALLER_THAN_0 == -1 should be true." && exit 1
       - name: Test if statement using and
         id: test_and
         if: ${{ env.LARGER_THAN_0 == 1 && env.SMALLER_THAN_0 == -1 }}
@@ -145,7 +145,7 @@ jobs:
       - name: Test if statement using and (again)
         if: ${{ env.LARGER_THAN_0 == 0 && env.SMALLER_THAN_0 == 0 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: LARGER_THAN_0 == 0 and SMALLER_THAN_0 == 0 should be false." && exit 1
       - name: Test if statement using or
         id: test_or
         if: ${{ env.LARGER_THAN_0 == 0 || env.SMALLER_THAN_0 == -1 }}
@@ -153,7 +153,7 @@ jobs:
       - name: Test if statement using or (again)
         if: ${{ env.LARGER_THAN_0 == 0 || env.SMALLER_THAN_0 == 0 }}
         run: |
-          echo "Test failed" && exit 1
+          echo "Test failed: LARGER_THAN_0 == 0 or SMALLER_THAN_0 == 0 should be false." && exit 1
       - name: Checking test result
         run: |
           if [[ $test_not_equal != 1 ]]; then
@@ -316,9 +316,9 @@ jobs:
               echo "graphql_url failed" && exit 1
           fi
 
-          if [[ "${{ github.job }}" != "test-contexts" ]]; then
-              echo "job failed" && exit 1
-          fi
+#         if [[ "${{ github.job }}" != "test-contexts" ]]; then
+#             echo "job failed" && exit 1
+#         fi
 
           if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
               echo "ref failed" && exit 1
@@ -605,3 +605,4 @@ jobs:
             exit(1);
           print("Test working-directory OK")
         working-directory: test
+        
